AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS Serverless Spring Boot 3 API - ind.qualitysoft.com::ecommerce-report
Globals:
  Api:
    EndpointConfiguration: REGIONAL

Resources:
  EcommerceReportFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: ind.qualitysoft.com.StreamLambdaHandler::handleRequest
      Runtime: java17
      CodeUri: .
      MemorySize: 512
      Policies: AWSLambdaBasicExecutionRole
      Timeout: 30
      Events:
        ProxyResource:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any

Outputs:
  EcommerceReportApi:
    Description: URL for application
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/ping'
    Export:
      Name: EcommerceReportApi
